!head #eee
午后15点整，监管所控制室内，机器人eebot徘徊于禁地。
随着脚步声的逐渐深入，eebot在什么生物面前停下脚步。
!pause
!head #4f0
「hihihi, This is eebot! °▽°」
!pause
!head #eee
不知是内置程序设定还是刻在脑海的记忆。
遇到聊天对象时，eebot总习惯性蹦出那句不变的欢迎语。
!pause
!head #fff
「……」
!pause
!head #4f0
「hi? 能听见eb说话吗？」
!pause
!head #fff
「……」
!pause
!head #eee
不管重复多少次，对面的生物始终没有回复。
!pause
隔着金色的鸟笼，立在竹竿上的一动不动的生物，
——是一只精致的白色小鸟。
!pause
那只鸟通体雪白，与eebot的吊带长裙一样纯洁。
!pause
还记之前，比eebot大了几天的WcyBot曾说：
!pause
!head #fcc
「那只是个摆件罢了，这么闪的笼子也只是装饰。」
*WCY的颜色我忘了 反正是粉色 拿个Beluga粉代替下
!pause
!head #eee
不止WcyBot，eebot的其它兄弟姐妹们也这么认为。
!pause
可那洁白的细腻的羽毛，炯炯有神的乌黑瞳孔，
……怎能让eebot轻易信服？
!pause
与其说是鸟，不如说……
那长长的颈脖使ta更像鸭子。
!pause
!head #fcc
「名字？管埋员Light说过，那是FoolishBird。」
!pause
!head #4f0
「FoolishBird？傻鸟？」
!pause
!head #eee
如此可爱的鸟竟会有如此可笑的名字。
!pause
!head #4f0
「不……其实，这个名字，很合适。」
!pause
!head #eee
不动的、无声的、呆的、傻的。
这几个词似乎常被相提并论。
!pause
eebot靠在围栏上，托着腮。
ta伸出手，想触碰那遥不可及的金色笼子。
!pause
eebot没放下手，也不想离开。
ta只是一直一直，一直一直凝视着傻鸟。
!pause
不知从何时起，嗡嗡的警报声已经在耳边回荡了。
!pause
eebot好似没注意危险的降临，又往前挪了几步。
!pause
!head #1fd
「靠nmb的，别tm给老子死这边发呆！」
*这句台词由zzChumo亲自献笔（被打
!pause
!head #eee
在eebot身后站着的，是和ta同年同日出生的zzbot。
!pause
虽然两人性格不合，
但zzbot是eebot在监管所最好的朋友。
!pause
WcyBot的性格有些傲慢，zzbot的脾气有些暴躁。
而eebot，只是个普通的、毫无特点的机器人。
!pause
eebot哇哇地叫，拼死命抓住围栏，
任由zzbot怎么拖都拖不走。
!pause
zzbot放开了eebot，握紧了拳头，
背后燃起了熊熊大火……就差把eebot揍飞了。
!pause
eebot瑟瑟发抖，冒着冷汗，僵在原地不敢动弹。
!pause
「滴滴嘟，滴滴嘟——」
!pause
陷入沉寂之时，eebot和zzbot才注意到警报声。
!pause
今天的eebot，还没来得及多看FoolishBird几眼，
……便被zzbot强行踹出了控制室。
!pause
另外，控制室是整个监管所电力的控制中心。
!pause
根据监管所规章第三条表示：
机器人不得随便入控制室，警报响起记过一次，
七次违反条例，机器人将会被依法销毁。
!pause
不幸的是，今天，是eebot最后一次机会。
!pause
在飞出监管所控制室后，eebot眼前一黑。
!pause
而后，ta便不知道发生什么了……
!pick 进入下一节 二、灰色的屋