!head #fff
「……嘎嘎嘎！」
!pause
!head #4f0
「……」
!pause
!head #fff
「嘎！嘎嘎嘎嘎嘎！！」
!pause
!head #eee
耳边传来似鸭似鹅的叫声，
受惊吓的eebot睁开眼，「唰」地坐起来。
!pause
环视四周，却发现ta身处陌生的地方。
而此刻eebot以瘫坐的姿势。
!pause
!head #fff
「Hi, eebot!」
!pause
「嘎~你终于醒了——」
!pause
!head #4f0
「……?!」
!pause
!head #fff
「不用害怕，这里是地下室，现在是安全的。」
!pause
!head #eee
在灰色的地板上，睡眼朦胧的eebot循声望去。
!pause
那只被ta一直惦记着、盼望某天开口说话的「工艺品」，
现在居然在eebot面前活蹦乱跳。
!pause
!head #4f0
「……是eb眼花了吗？」
!pause
!head #eee
eebot使劲揉眼、摇头，差点选择再睡一觉。
!pause
可那只鸟依然在眼前，微笑、转圈圈、
用毛茸茸的翅膀竖起大拇指。
!pause
!head #fff
「eebot，当然不是！
在你面前的可是大名鼎鼎的FoolishB……」
!pause
!head #4f0
「wowow! 说话了说话了——°▽°」
!pause
!head #eee
FoolishBird话音未落，就被eebot举了起来。
!pause
!head #fff
「F**k!!!」
!pause
!head #eee
半悬空的FoolishBird先是一阵骂骂咧咧，
又是一阵颤颤巍巍、哆哆嗦嗦。
!pause
知道FoolishBird恐高后，eebot才把ta放下。
!pause
!head #fff
「……」
!pause
「……很奇怪吧，身为鸟，居然会恐高。」
!pause
!head #eee
原本还很神气的FoolishBird，现在看上去十分沮丧。
!pause
放下FoolishBird的eebot，
对这么待「救命恩鸟」抱着歉意，于是安慰：
!pause
!head #4f0
「对、对不起……不过，大家都有弱点，eb也有。」
!pause
!head #fff
「eebot？比如说？」
!pause
!head #4f0
「不能接受强光照射！特别是……黑暗中特别明亮的灯火。」
!pause
「对比度很强的光，绝对不行！」
!pause
!head #eee
果然，FoolishBird的好奇心一下子被提起了。
!pause
前头是聚精会神的FoolishBird，
后方是一本正经的eebot。
!pause
!head #fff
「……噗……噗哈哈哈哈！eebot，这有什么的——」
!pause
!head #eee
虽然不是什么很好的理由，
但FoolishBird总算是打起精神了。
!pause
不过，FoolishBird没有信以为真。
——ta不认为机器人会有弱点。
!pause
而eebot欲言又止，最后也没再解释下去了。
!pause
eebot询问FoolishBird为什么知道ta的名字。
!pause
FoolishBird回答eebot说，ta的名字绣在裙子上。
!pause
稍提一嘴，监管所里所有机器人，
都有属于自己的一套衣服，衣服上绣有名字。
!pause
从机器人「出生」起伴随到大，衣服还会随体型变化。
!pause
例如，WcyBot是粉红色卫衣，zzbot是淡蓝色卫衣。
而eebot，则穿着纯白色吊带长裙。
!pause
但「出生」并不是普通意义上的出生。
!pause
eebot不记得是何年何月出生、
何年何月居住在监管所了。
!pause
或许，自始至终，都是以这个外貌、这个名字存在。
!pause
其它机器人兄弟姐妹也是。
大家没有任何变化、不知存在这世上多久了。
!pause
每天的生活是如同白开水般的日常，玩、学习、睡觉。
!pause
虽然，机器人们会思考，拥有意识；有味觉，喜欢美食。
!pause
但即便饭食不进也不会饿死，
即便滴水不饮也不会渴死。
!pause
!head #4f0
「真是无聊啊。」
!pause
!head #eee
时而eebot会如此想，
向鸟笼里一动不动的鸟抱怨道。
!pause
不过，待到朋友们去找ta玩，
eebot又马上打断了不开心的思绪。
!pause
!head #fff
「eebot，想起为什么在这里了吗？」
!pause
!head #eee
地下室，顾名思义就是与地上相反的地方。
!pause
在片刻的冷静后，
eebot才想起那最后一次记过的机会。
!pause
在被zzbot拖出控制室后，ta失去了意识。
!pause
之后醒来，就在这里了。
!pause
!head #4f0
「WB……zb……真是对不起了……」
!pause
!head #eee
对于一直在劝说ta的朋友们，eebot是怀有歉意的。
!pause
!head #fff
「嘎？」
!pause
!head #4f0
「好！eb决定了……」
!pause
!head #fff
「逃跑！」
!pause
!head #4f0
「没错！°▽°」
!pause
!head #fff
「好！eebot，很有精神。」
!pause
!head #eee
FoolishBird抢答了。
!pause
!head #eee
eebot比了一个V字形手势，机器人和鸟双双跳起来。
!pause
!head #4f0
「……咦？为什么FB知道eb想逃跑？」
!pause
!head #eee
这才发现有什么奇怪地方的eebot，满脸写着「不对劲」。
!pause
可FoolishBird只是意味深长地笑笑，没说话。
!pause
毕竟，在FoolishBird的眼睛里，更加奇怪的是：
!pause
在七次记过达成的那瞬间，金色的鸟笼轰然炸裂。
!pause
被封印在UWULAND的FoolishBird，
最终取回了意识、取回了身体自主权。
!pause
UWULAND上唯一知道真相的鸟，重获新生——
!pause
但是，傻鸟，tmd失去了记忆。
!pick 进入下一节 三、绿色的门