!head #eee
eebot内置的钟表，
在不知不觉中，已经走到了夜晚21点整。
!pause
离eebot最后在控制室早就过去了6小时。
期间，ta一直处于昏迷状况。
!pause
eebot明白，ta再没机会留在监管所、
再没机会见到WcyBot和zzbot了。
!pause
FoolishBird也是，ta本身就不是该取回意识的生物。
!pause
当然，想法归想法。
要是想逃跑，它们还得制定计划。
!pause
!head #fff
「eebot，你知道监管所处于哪里吗？」
!pause
!head #4f0
「……在小岛上？四面环海？」
!pause
!head #fff
「嘎~完全正确！」
!pause
!head #eee
曾几何时，eebot萌生过不止一两次逃跑的想法。
!pause
eebot也因此做过一些调查……可是，极少。
!pause
eebot查找资料的途径，也就只有在监管所内部了。
!pause
!head #fff
「不过，eebot，还不够详细。」
!pause
「我们现在在LINK海中心的GREEN岛上。」
!pause
!head #eee
FoolishBird看起来十分自信，挺直了胸膛。
!pause
ta对监管所的地理位置所在竟如此清楚。
!pause
!head #4f0
「wowow?! FB……是怎么知道的？」
!pause
!head #eee
FoolishBird耸了耸肩，摇了摇头，
试图思考脑海里为何会有这些记忆。
!pause
!head #eee
但片刻后，ta还是放弃了。
!pause
在一番了解后，
eebot才知道FoolishBird失去了大部分记忆。
!pause
FoolishBird提议说，
留到深夜23点，再通过「秘密途径」离开监管所。
!pause
为什么深夜23点？
答：21点机器人休眠时间，22点管理员休息时间。
!pause
如何瞒天过海？
答：走监控缺失的暗道。
!pause
暗道在哪？
答：绿色的门会指引它们。
!pause
出去后是哪？
答：监管所后方，面朝大海。
!pause
没有船怎么办？
答：当然有，在想象里……
!pause
哦不，FoolishBird自知何处。
!pause
之后去哪？
答：看船漂去哪里……
!pause
呃，是的，在监管所之外，
就是FoolishBird记忆缺失的部分。
!pause
eebot紧盯着FoolishBird，最后呜咽着向后倒去。
!pause
虽然FoolishBird疑点重重，但eebot还是选择了相信。
!pause
eebot明白，ta和FoolishBird，从相遇到相识的不易。
!pause
那么，在那之前，它们会在地下室探索。
——所幸地下室是相对而言安全的。
!pause
据FoolishBird所说，
除监管所的管埋员外，不会有更多人知道地下室的存在。
!pause
而管埋员，也鲜少踏足此地。
!pause
eebot与FoolishBird所处的是地下室中心。
!pause
除了灰色的地板和墙壁，这里空无一物。
!pause
但地下室其实不小。
地下室中心的墙面上，一扇扇门后充满着未知。
!pause
而绝大部分房间是杂物室。
有的是空室，门后的门后还有一扇扇门。
!pause
!head #4f0
「aa，绿色的门到底在哪，eb感觉要迷路了。」
!pause
!head #eee
eebot托着FoolishBird，走得筋疲力尽。
!pause
!head #fff
「bzd……」
!pause
!head #eee
在不知打开了多少扇门后，映入眼帘的是……
……最初的地下室中心。
!pause
FoolishBird站在eebot肩上，
用ta毛茸茸的翅膀，再次竖起了大拇指。
!pause
!head #fff
「……但是，eebot，我们已经迷路了。」
!pause
!head #eee
eebot瘫倒在地，直接躺下，原地打滚。
!pause
突然，在eebot的手碰到的地方——
地上一块小小的砖板，下沉了5厘米。
!pause
伴随着什么破碎的声音，周围的某一扇门，染上了绿色。
!pause
eebot与FoolishBird相视一楞，走上前去。
!pause
——绿色的门没有把手，门上的油漆有些斑驳。
!pause
当eebot和FoolishBird同时触碰时，
门就好似被一股无形的推力推开了。
!pause
紧接着是一条长而狭窄的铁制楼梯，天花板也很矮。
就连不到150cm的eebot，都要弯着腰艰难地走。
!pause
eebot的怀里抱着FoolishBird……看起来快睡着了。
!pause
或许那就是FoolishBird所说的，没有监控的暗道。
!pause
只不过，通行度更加出乎意料罢了。
!pause
尽头又是一扇绿色的门，但似乎有些许异样的不同：
无论如何触碰，门都不再自动打开了。
!pause
然后，身旁的墙上，隐约浮现出一行密文：
「Ym90cyBhbmQgY2hpcHM=」
!pause
!head #4f0
「这是？」
!pause
!head #eee
FoolishBird盯着末尾的等于号，陷入沉思。
!pause
而eebot，则一头雾水。
!pause
!head #fff
「eebot，兴许是Base64加密。」
!pause
!head #4f0
「好吧~那eb试试。」
!pause
!head #eee
FoolishBird是只见多识广的鸟，但并不会Base64解码。
eebot虽没FoolishBird那么聪明，但功能要多得多。
!pause
!head #eee
所以，解码的结果是？
!pick 「bots&chips」 四、蓝色的海